import "./globals.css";
import { Lobster } from "next/font/google";

const inter = Lobster({ subsets: ["latin"],
  weight:['400'] 

});





export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
      className={inter.className}
      >
        {children}
      </body>
    </html>
  );
}
